### ISSUE TITLE
Partially working nested class name prefixing

### ISSUE THREAD

**Issue by bytasv** [marceloucker/postcss-prefixer#2]
Given this input:
```css
.hello:not([class*="left labeled"]) {
 border-radius: 3rem;
}
```
This plugin outputs:
```css
.prefix-hello:not([class*="prefix-left labeled"]) {
 border-radius: 3rem;
}
```

See `labeled` class is not prefixed.
