### ISSUE TITLE
Keyword of `class` can get transformed to `classundefinedundefinedundefined`

### ISSUE THREAD

**Issue by patdx** [marceloucker/postcss-prefixer#28]
I noticed an interesting bug and narrowed it down to this plugin, here is minimum size reproduction:

https://github.com/patdx/postcss-prefix-bug

In:

```css
/* https://github.com/twbs/bootstrap/blob/55a0f9af2738daafe8d961ca35c22800c710bb27/dist/css/bootstrap.css#L212 */

a:not([href]):not([class]),
a:not([href]):not([class]):hover {
  color: inherit;
  text-decoration: none;
}
```

Out:

```css
/* https://github.com/twbs/bootstrap/blob/55a0f9af2738daafe8d961ca35c22800c710bb27/dist/css/bootstrap.css#L212 */

a:not([href]):not([classundefinedundefinedundefined]),
a:not([href]):not([classundefinedundefinedundefined]):hover {
  color: inherit;
  text-decoration: none;
}
```

In this case the plugin should not have change this code at all, I think?

I added some console logs to the plugin, getting this result:

```sh
➜  postcss-prefix-bug git:(main) npm start

> postcss-prefix-bug@1.0.0 start /Users/pm/dev/postcss-prefix-bug
> postcss src.css -o dist.css

parseAttrSelector({"type":"attribute","content":"href"}) -> {"type":"href","classes":[]}
parseAttrSelector({"type":"attribute","content":"class"}) -> {"type":"class","classes":[]}
attrStringify({"type":"class","classes":[]}) -> classundefinedundefinedundefined
parseAttrSelector({"type":"attribute","content":"href"}) -> {"type":"href","classes":[]}
parseAttrSelector({"type":"attribute","content":"class"}) -> {"type":"class","classes":[]}
attrStringify({"type":"class","classes":[]}) -> classundefinedundefinedundefined
```

It think the bug may be in the line right after `parseAttrSelector` is called:

```
    if (!['class', 'id'].includes(type)) return node;
```

However, I'm not familiar with this kind of CSS selector, so I'm totally sure how/what this part of the code is doing 😅 

Alternatively, perhaps the solution is to have a fallback for undefined values inside attrStringify?

```diff
  attrStringify({
    type, operator, head, classes, foot,
  }) {
-    return `${type}${operator}${head}${classes.join(' ')}${foot}`;
+    return `${type}${operator ?? ''}${head ?? ''}${classes?.join(' ') ?? ''}${foot ?? ''}`;
  },
```
