### ISSUE TITLE
add extra class to element selectors

### ISSUE THREAD

**Issue by milahu** [marceloucker/postcss-prefixer#48]
actual result

```css
body { margin: 1; }
.some-prefix-some-class { margin: 2; }
```

expected result

```css
body.some-prefix { margin: 1; }
.some-prefix-some-class { margin: 2; }
```

why?
this is necessary to mix different css frameworks
with custom default styles for elements

different than [postcss-prefix-selector](https://www.npmjs.com/package/postcss-prefix-selector)

<details>

```js
const fs = require('fs');
const postcss = require('postcss');
const prefixer = require('postcss-prefixer');

//const input = fs.readFileSync('src.css',  'utf-8');

const input = [
  "body { margin: 1; }",
  ".some-class { margin: 2; }",
].join("\n");

const output = postcss([
  prefixer({
        prefix: 'some-prefix-',
        //ignore: [ /selector-/, '.ignore', '#ignore' ]
    })
]).process(input);

console.log(output.toString());

```
